project:
  type: website
  render:
  - "*.qmd"
  - "!res/"
  - "!scripts/"
  output-dir: "_site"

website:
  title: "PathSIG Presents: #PathMatch24 PD Panel"
  navbar:
    left:
      - event.qmd
      - text: "Programs"
        file: programs/index.qmd
      - text: "Path SIG Board"
        file: board/index.qmd
      - about.qmd

format:
  html:
    theme: cerulean
    css: styles.css
